### ISSUE TITLE
Missing Method Exception was Unhandled

### ISSUE THREAD

**Issue by ggstamm** [KyleGobel/Hipchat-CS#27]
Hello, I have an issue, when I use this line below:
_"HipchatClient client = new HipchatClient();"_

This is the exception:
_

> An unhandled exception of type 'System.MissingMethodException' occurred in HipchatApiV2.dll
> 
> Additional information: Method not found: 'Void ServiceStack.Text.JsConfig`1.set_DeSerializeFn(System.Func`2<System.String,!0>)'.

_

I'm newbie with C#, and don't know how to make this work.

My imports:
using System;
using System.Runtime.InteropServices;
using HipchatApiV2;
using HipchatApiV2.Requests;
using Xunit;
using ServiceStack.Text;

**Comment by ggstamm** [comment]
My packages:
<package id="Hipchat-CS" version="0.0.52" targetFramework="net45" />
<package id="ServiceStack.Text" version="4.0.50" targetFramework="net45" />

**Comment by ggstamm** [comment]
My packages:
```
<package id="Hipchat-CS" version="0.0.52" targetFramework="net45" />
<package id="ServiceStack.Text" version="4.0.50" targetFramework="net45" />
```

**Comment by haydenthrash** [comment]
@ggstamm go into your Nuget Package Manager and uninstall ServiceStack.Text v4.0.60, then manually install version 4.0.56.  That worked for me.

**Comment by haydenthrash** [comment]
Install ServiceStat.Text version 4.0.56.  That worked for me.  Hope this helps! @ggstamm

**Comment by KyleGobel** [comment]
These errors are normally from dependency version mismatchs.  Hipchat CS was built against ServiceStack 4.0.56.  

I think I probably need to pin the dependency to a specific version.

Doing what haydenthrashsaid should fix the issue though in the meantime.

**Comment by ggstamm** [comment]
Thanks for the reply, but I still have the same error, I'm starting to think that it's something about my Visual Studio :(.

I create a Visual C# -> Console Application.

> An unhandled exception of type 'System.MissingMethodException' occurred in HipchatApiV2.dll
>Additional information: Method not found: 'Void >ServiceStack.Text.JsConfig`1.set_DeSerializeFn(System.Func`2<System.String,!0>)'.

Packages
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Hipchat-CS" version="0.0.52" targetFramework="net45" />
  <package id="ServiceStack.Text" version="4.0.56" targetFramework="net45" />
</packages>`

Code:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HipchatApiV2;

namespace Console_HipChat_CS
{
    class Program
    {
        static void Main(string[] args)
        {
            string apikey = My API here;
            var client = new HipchatClient(apikey);
            client.SendNotification("Test", "Testing"); 
        }
    }
}
```

Sorry for disturbing you.
